services:
  terraform:
    container_name: 'terraform'
    build:  
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./src
        target: /src
    tty: true